export const sriLankanCities = [
    "Colombo", "Kandy", "Galle", "Jaffna", "Negombo", "Anuradhapura", "Matara", 
    "Ratnapura", "Trincomalee", "Batticaloa", "Kurunegala", "Badulla", "Nuwara Eliya", 
    "Kalutara", "Gampaha", "Hambantota", "Vavuniya", "Mannar", "Puttalam", "Polonnaruwa", 
    "Ampara", "Moneragala", "Kilinochchi", "Mullaitivu", "Matale", "Kegalle", 
    "Bandarawela", "Wattala", "Dehiwala", "Moratuwa", "Sri Jayawardenepura Kotte", 
    "Katunayake", "Avissawella", "Panadura", "Maharagama", "Horana", "Nawalapitiya", 
    "Hatton", "Talawakele", "Weligama", "Beruwala", "Ja-Ela", "Peliyagoda", 
    "Kotikawatta", "Battaramulla", "Hikkaduwa", "Kadawatha", "Kelaniya", "Nugegoda", 
    "Kotte", "Homagama", "Embilipitiya", "Tangalle", "Piliyandala", "Maharagama", 
    "Kadugannawa", "Balangoda", "Chilaw", "Ambalangoda", "Kuliyapitiya", "Wennappuwa", 
    "Minuwangoda", "Bandaragama", "Mawanella", "Yakkala", "Dankotuwa", "Nattandiya", 
    "Mirigama", "Pannala", "Warakapola", "Kegalle", "Ragama", "Aluthgama", "Payagala", 
    "Dambulla", "Haputale", "Tissamaharama", "Kataragama", "Kalmunai", "Eravur", 
    "Valvettithurai", "Chunnakam", "Point Pedro", "Vavuniya", "Kilinochchi", "Mannar", 
    "Nuwara Eliya", "Haputale", "Hatton", "Talawakele", "Dikwella", "Tangalle", 
    "Hambantota", "Beruwala", "Bentota", "Matugama", "Ambalangoda", "Hikkaduwa", 
    "Gonapinuwala", "Elpitiya", "Balapitiya", "Dodangoda", "Kalutara", "Beruwala", 
    "Wadduwa", "Bandaragama", "Ingiriya", "Horana", "Panadura", "Moratuwa", "Ratmalana", 
    "Kesbewa", "Piliyandala", "Boralesgamuwa", "Maharagama", "Homagama", "Kottawa", 
    "Athurugiriya", "Battaramulla", "Thalawathugoda", "Kotikawatta", "Malabe", 
    "Wattala", "Peliyagoda", "Kelaniya", "Kiribathgoda", "Ja-Ela", "Seeduwa", 
    "Katunayake", "Negombo", "Kurana", "Mawathagama", "Pannipitiya", "Nugegoda", 
    "Sri Jayawardenepura Kotte", "Rajagiriya", "Dehiwala", "Mount Lavinia", 
    "Galkissa", "Nawala", "Piliyandala", "Maharagama", "Boralesgamuwa", "Ratmalana", 
    "Moratuwa", "Panadura", "Kalutara", "Wadduwa", "Bandaragama", "Matara", 
    "Weligama", "Dickwella", "Devinuwara", "Deniyaya", "Gandara", "Akuressa", 
    "Hakmana", "Kamburupitiya", "Dondra", "Tangalle", "Ambalantota", "Embilipitiya", 
    "Tissamaharama", "Kataragama", "Weeraketiya", "Walasmulla", "Beliatta", 
    "Middeniya", "Kekirawa", "Kahatagasdigiliya", "Medawachchiya", "Mihintale", 
    "Padaviya", "Eppawala", "Palagala", "Horowpothana", "Ipalogama", "Galnewa", 
    "Galenbindunuwewa", "Polonnaruwa", "Hingurakgoda", "Medirigiriya", "Giritale", 
    "Somawathiya", "Bakamoona", "Aralaganwila", "Dimbulagala", "Manampitiya", 
    "Dehiattakandiya", "Ampara", "Kalmunai", "Akkaraipattu", "Sainthamaruthu", 
    "Sammanthurai", "Uhana", "Mahaoya", "Padiyatalawa", "Damana", "Thirukkovil", 
    "Addalaichenai", "Oluvil", "Karaitivu", "Kaluwanchikudy", "Batticaloa", 
    "Valaichchenai", "Eravur", "Kattankudy", "Kalkudah", "Chenkalady", "Mannar", 
    "Vavuniya", "Kilinochchi", "Mullaitivu", "Oddusuddan", "Puthukkudiyiruppu", 
    "Mallavi", "Thunukkai", "Murungan", "Pesalai", "Silavatturai", "Madhu", 
    "Pallai", "Pooneryn", "Vellankulam", "Jaffna", "Nallur", "Chavakachcheri", 
    "Point Pedro", "Valvettithurai", "Karainagar", "Velanai", "Kayts", "Pungudutivu", 
    "Delft", "Achchuveli", "Atchuvely", "Chunnakam", "Palai", "Manipay", 
    "Tellippalai", "Kankesanthurai", "Mallakam", "Vaddukoddai", "Puttur", 
    "Valikamam", "Kopay", "Neduntivu", "Kurunegala", "Kuliyapitiya", "Pannala", 
    "Narammala", "Galgamuwa", "Polgahawela", "Wariyapola", "Melsiripura", 
    "Alawwa", "Hettipola", "Giriulla", "Nikaweratiya", "Ibbagamuwa", "Maho", 
    "Katupotha", "Yapahuwa", "Gampola", "Nawalapitiya", "Hatton", "Talawakele", 
    "Pussellawa", "Kadugannawa", "Ududumbara", "Akurana", "Wattegama", "Matale", 
    "Dambulla", "Sigiriya", "Rattota", "Ukuwela", "Galewela", "Naula", 
    "Pallepola", "Ambatenna", "Madawala", "Kegalle", "Mawanella", "Warakapola", 
    "Rambukkana", "Galigamuwa", "Bulathkohupitiya", "Deraniyagala", "Dehiowita", 
    "Avissawella", "Yatiyanthota", "Ruwanwella", "Kithulgala", "Nawalapitiya", 
    "Hatton", "Talawakele", "Deniyaya", "Ratnapura", "Balangoda", "Embilipitiya", 
    "Pelmadulla", "Opanayake", "Rakwana", "Godakawela", "Weligepola", "Kolonne", 
    "Agalawatta", "Kiriella", "Kuruwita", "Kalawana", "Ayagama", "Eheliyagoda", 
    "Nivithigala", "Elapatha", "Imbulpe", "Parakaduwa", "Pambahinna", "Kahawatta", 
    "Batugedara", "Ambilipitiya", "Badulla", "Bandarawela", "Welimada", "Ella", 
    "Hali Ela", "Haputale", "Passara", "Mahiyanganaya", "Bibila", "Moneragala", 
    "Wellawaya", "Buttala", "Kataragama", "Tanamalwila", "Siyambalanduwa", 
    "Madulla", "Medagama", "Dambagalla", "Hambegamuwa", "Padiyathalawa", 
    "Aralaganwila", "Dehiattakandiya", "Maduru Oya", "Hasalaka", "Lunugala"
  ];
  